name: Build EXE with Nuitka

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "arr_interest_calculator.py"
      - "requirements.txt"
      - ".github/workflows/build.yml"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # change if you use a different Python version
          architecture: "x64"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") { pip install -r requirements.txt }
          pip install nuitka

      - name: Build with Nuitka
        shell: pwsh
        run: |
          python -m nuitka `
            --onefile `
            --assume-yes-for-downloads `
            --output-dir=build `
            arr_interest_calculator_fixed.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: arr-interest-calculator-exe
          path: build\arr_interest_calculator.exe
